version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  auth:
    build: ./auth
    environment:
      PORT: "80"
      VIRTUAL_HOST: "auth.local"
    expose:
      - "80"

  profile:
    build: ./profile
    environment:
      PORT: "3001"
      VIRTUAL_HOST: "profile.local"
    expose:
      - "3001"

  proxy:
    build: ./proxy
    environment:
      PORT: "3002"
      VIRTUAL_HOST: "proxy.local"
    links:
      - auth:auth
    expose:
      - "3002"
    depends_on:
      - auth
